@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "HomeChef Storage" #F4F6F6{
Class "<<interface>>\nHomeChefStorage" as HomeChefStorage
Class JsonHomeChefStorage
Class JsonSerializableHomeChef
Class JsonAdaptedOrder
Class JsonAdaptedTag
}

package "MenuBook Storage" #F4F6F6{
Class "<<interface>>\nMenuBookStorage" as MenuBookStorage
Class JsonMenuBookStorage
Class JsonSerializableMenuBook
Class JsonAdaptedMenuItem
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
Storage ..|> UserPrefsStorage
Storage ..|> HomeChefStorage
Storage ..|> MenuBookStorage

StorageManager .left.> "1" HomeChefStorage
StorageManager .down.> "1" UserPrefsStorage
StorageManager .right.> "1" MenuBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonHomeChefStorage .up.|> HomeChefStorage
JsonMenuBookStorage .up.|> MenuBookStorage
JsonHomeChefStorage ..> JsonSerializableHomeChef
JsonMenuBookStorage ..> JsonSerializableMenuBook
JsonSerializableHomeChef --> "*" JsonAdaptedOrder
JsonSerializableMenuBook --> "*" JsonAdaptedMenuItem
JsonAdaptedOrder --> "*" JsonAdaptedTag


@enduml
